### ISSUE TITLE
Fix formatting in Yellow Box

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/panicbutton.io#10]
See box on this page: http://panicinitiative.github.io/panicbutton.io/pact-activities/pact-activities-05-pact-action-plan.html

**Comment by naturalshine** [comment]
@jmatsushita Unless I'm missing something, the issue is that markdown formatting is not valid inside of HTML block elements; here, md formatting was wrapped inside a <pre><code>div</code></pre>. I tried to change the <pre><code>div</code></pre> to a <pre><code>span</code></pre>, but this change did not keep the yellow border in tact. So, I removed the enclosing yellow border entirely, which does not affect the printing of the page -- is this an ok solution? Another option is to add HTML formatting instead of markdown formatting on the text (a simple heading and <ul> would work).

**Comment by jmatsushita** [comment]
Fixed with kramdown and settings. http://panicinitiative.github.io/panicbutton.io/pact-activities/pact-activities-05-pact-action-plan.html
