### ISSUE TITLE
imPact Game Addition

### ISSUE THREAD

**Issue by naturalshine** [PanicInitiative/panicbutton.io#11]
I added the imPACT game to the "Training Kit" as we discussed on Monday. 

Some notes: 
- I feel that the [landing page](http://panicinitiative.github.io/panicbutton.io/impact-rules/impact-rules.html) of the game is too long -- the "rules" are quite lengthy, and then the cards beneath the rules stretch on and on as well. I would argue to embed the rules one page deeper, making them a link at the top of the game card table of contents. 
- I used a question mark to link to the "How to print" page, but I think reusing one of the existing kit-related icons might look better. 
- For printing, each [card](http://panicinitiative.github.io/panicbutton.io/pact-cards/pact-cards-01-hrd.html) in the game is headed by an extremely large "back of card" image -- I would move to remove this image, but wanted to remain faithful to the existing code in the first iteration -- what do you think? 
- Note that none of the download links work yet; I'm making new PDFs with the yellow counter at the top of the main cards in the kit!

**Comment by jimmylogan** [comment]
Hi,

- Agree that it is too long and that we should move some of the content one page deeper. However, I think that we should address this in the following  ways:

imPact Game Overview Page:
(a) Rename the landing page from  'imPACT Game Rules' to 'imPACT Game Overview'.

b) Keep the wording in sections 1 and  2 on the Game Overview page.

(c) Move the subsequent wording (from game  progress onwards) onto the  next page and link to these as the 'imPACT Game Rules'.

(d) Keep the cards on the imPact Game Overview page so  that they are displayed below the end of section 2 in horizontal rows so  they don't make the page too long - about 4 or 5 per row.   

(e) On the the cards icons  on  the  Impact Game  Overview page,  it would be good for them to display the actual  cards for each character on the  game,  rather than the same image. These are the images that are in the original  pdfs. There is no need  to include the bio  but we should leave the name of the character under each card.

(f) Change  the name in the icon on the  'Training Kit' page which links to the Game Overview Page as  'imPACT Game Overview'. Also, below that, create another icon for the 'imPact Game Rules' page. Please remove  the methodology section and  include the following text above the line next to the Game Overview page icon saying :

"imPACT Game where teams role play setting up, setting off and responding to the Panic Button in real life. Get an overview  of the game and browse the cards."

(g)  Next to the Game Rules icon,  you should put a similar entry saying:

"Learn the rules of the imPACT Game."

Card Pages:
(h) We need  to change  the image  for all the card pages as currently the image is not the same as the pdf e.g. [here:] (http://panicinitiative.github.io/panicbutton.io/pact-cards/pact-cards-01-hrd.html). The image should also be smaller to about 25% of its size. Let's leave the back for the time being but consider working on it if this change doesn't work. 

(i) Some of  these images contains important information. E.g.  some of the pages, e,g,  [here](http://panicinitiative.github.io/panicbutton.io/pact-cards/pact-cards-03-head-of-nhrdc.html) have a text saying 'token' underneath the current image. This needs to be removed once  the correct image is put in.

- Great about the pdfs and about the printing  icon which looks good.

Thanks!

James

**Comment by naturalshine** [comment]
I think that these are done with the exception of putting in unique images for each of the character cards -- am working on that and will send the issue to review "officially" when that's done. But if you want to check the other aspects of this issue in the mean time, it's ready. 

I removed the "Token" section in anticipation of the coming images already, but it's very simple to put back in if we want it for some reason.

**Comment by naturalshine** [comment]
Hi @jimmylogan ! I'm looking for the character images and realising I don't know what they are, precisely -- is this the [right repo](https://github.com/the-engine-room/PACT-kit/tree/gh-pages/assets/img)? (Images images prefixed "gc_") Or is there another repo that I'm no aware of? Thanks :)

**Comment by jimmylogan** [comment]
Hi @niccs, I haven't got access to the .zip file right now to compare but
think that these look like they are missing some details. Will review and
get back in a few hours. J

**Comment by jimmylogan** [comment]
HI @niccs, I've had a look at the images on that repo and compared them to the one on the zip and they are largely the same except for a few differences (most obviously 9-2 and 10-2 which should not be used). 

Their characters are as follows:

gc_1-1 = Human Right Defender
gc_2-1 = NGO Security Focal Point
gc_2-2 = Head of the National Human Rights Defenders Coalition*
gc_3-1 = Lawyer*
gc_3-2 = Warden of Detention Center*
gc_4-1 = Campaigning Colleague
gc_4-2 = EU Mission Delegate*
gc_5-1 = Security Focal Point for the National Human Rights Defenders Coalition
gc_5-2 =Coalition's Communications Officer*
gc_6-1 = Techie Colleague
gc_6-2 = IT Director*
gc_7-1 = Friend
gc_7-2 = Family Member*
gc_8-1 = Community Outreach Colleague
gc_8-2 = INGO Representative*
gc_9-1 = Partner NGO Member*
gc_9-2 = No equivalent in the imPACT game
gc_10-1 = NGO Communications Officer*
gc_10-2 = No equivalent in the imPACT game

- Where there is an asterisk, it means that there is a token or instruction label on the top half of the image and I think that it should be removed if at all possible. 

- I also agree about your earlier suggestion that the top half (which contains that token) should be reduced so that the image is not so tall (if you can still keep the frame around the image). 

- Finally, I think that arranging the images  in horizontal rows looks great apart from the fact that there are 17 images and thus a single one hangs at the bottom (the NGO Communications Officer. I suggest that we keep the first image (1-1 Human Rights Defender) in a row of it own with that in the center and then have the four rows below that, starting with 2-1 NGO Security Focal Point. 

I hope that this is clear! Thanks, J

**Comment by naturalshine** [comment]
Hi @jimmylogan -- great -- thank you for clarifying this! I will crop the images down a bit before inserting them, then -- but a few quick question first: 

What do you mean by "keep the frame around the image"? Do you mean cropping from the *middle* of the image, and retaining the top half (on those without tokens/instruction labels)? In this case, is the "frame" you're referring to the thin black line with four yellow corners? 

And no problem with the new grid configuration; I fixed it already and will push it with the images when they've been placed into the site. 

Ah, also, you've been at'ing someone else in these replies - my github handle is @naturalshine :)

**Comment by jimmylogan** [comment]
Oh no, sorry about that @naturalshine!

I mean cropping from the middle but keeping the bottom half (the bit with the picture representing the character).

The frame is the the thin black line with the yellow corners bordering the image- I'm not sure how easy it is to remove the top half without losing the top edge of that border, however.

Thanks a lot,

James

**Comment by naturalshine** [comment]
Hey @jimmylogan -- put in the new PNGs and changed around the grid -- just let me know what you think when you have a chance to review! The PNGs were a bit tricky to crop, because of the light grey diagonal lines running through them. I tried to make subtle borders.

**Comment by jimmylogan** [comment]
Hi @naturalshine - the cropping looks good, thanks for that. 

Having reviewed the images on the [Impact Game Overview](http://panicinitiative.github.io/panicbutton.io/impact-rules/impact-overview.html), I think that (a) they are still too long, and (b) that we should remove the upper image (the 'key') where they exist. 

Can you:

-  Crop the top half of the images out (but retaining the upper edge of the border) so that they become more of a square shape.?

- Remove the top picture when you are doing this for those of the images that have two in the card?  So, for example, for the IT Director, there will only be the black key in the yellow circle and not the yellow key in the dotted white circle. 

The images with the top picture are the following:

gc_2-2 = Head of the National Human Rights Defenders Coalition
gc_3-2 = Warden of Detention Center
gc_4-2 = EU Mission Delegate
gc_5-2 =Coalition's Communications Officer
gc_6-2 = IT Director
gc_7-2 = Family Member
gc_8-2 = INGO Representative
gc_9-1 = Partner NGO Member
gc_10-1 = NGO Communications Officer

You were right about them being too long and I think that, after this, we'll be able to put this one to bed. Thanks!

**Comment by naturalshine** [comment]
Hi @jimmylogan ! Sure, I agree... I've re-cropped the images, and they're live -- what do you think?

**Comment by jimmylogan** [comment]
They look brilliant!  Thanks, J
