### ISSUE TITLE
Add Previous Next buttons to Kit pages

### ISSUE THREAD

**Issue by jmatsushita** [PanicInitiative/panicbutton.io#6]

**Comment by jmatsushita** [comment]
http://iilab.github.io/teampanicbutton.github.io/pact-activities/pact-activities-01-introduction.html

![image](https://cloud.githubusercontent.com/assets/356097/11423405/5f74e00e-9444-11e5-8330-082685993717.png)

There's a Next button in the bottom right.

**Comment by naturalshine** [comment]
Per waffler update, ready for review -- removed "home" arrow and changed styling (very simply) and positioning of prev/next buttons

**Comment by naturalshine** [comment]
A further question, on this, though --> the prev/next links are messed up on the bottom section of the guide, **Panic Button Application** in [App Setup](http://panicinitiative.github.io/panicbutton.io/pact-app/pact-app-01-app-setup-and-practice.html) and [Digital mobile security](http://panicinitiative.github.io/panicbutton.io/pact-app/pact-app-02-risk-and-mitigation-android.html), which is also still lacking content. Should they just point to each other?

**Comment by naturalshine** [comment]
Fixed arrows again today -- now they appear inside white area at bottom of the posts. I incorporated the yellow "counter" at the top of the posts in the "Training Activities" and "Panic Button Application" sections, per the Engine Room's Github account, which had the counter incorporated (see [here](http://the-engine-room.github.io/PACT-kit/pact%20activities/Introduction/) ). Because the counter goes up to seven, I linked the "Training Activities" and "Panic Button Application" posts to one another via the prev/next arrows, but these links are easily removable if not desired.

**Comment by naturalshine** [comment]
Also added "home" top arrow on the Game Cards in the imPact game (like [this](http://panicinitiative.github.io/panicbutton.io/pact-cards/pact-cards-01-hrd.html). This arrow navigates back to the main game page, [here](http://panicinitiative.github.io/panicbutton.io/impact-rules/impact-rules.html).

**Comment by jmatsushita** [comment]
Awesome progress @naturalshine ! Thanks!!!

**Comment by jmatsushita** [comment]
Ok thinking about it, maybe there's no need for the Up arrow. Let's remove it!

**Comment by naturalshine** [comment]
Removed! I think this one is done :)
